server:
  port: 8071
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config"
          search-locations: "file:///Users//shruti_agarwal1//Documents//config"